### ISSUE TITLE
The 'x' between resolutions sometimes uses wrong symbol

### ISSUE THREAD

**Issue by wkumik** [OpenIPC/msposd#20]
instead of an'x' a height symbol shows up for some resolutions. Using the latest Mario AIO firmware, INAV

**Comment by tipoman9** [comment]
Can you explain where exactly you see this wrong symbol? A screenshot or more detailed description, please.

**Comment by henkwiedig** [comment]
Please add some information or i will close this one.

**Comment by henkwiedig** [comment]
Closeing this one due to response.
