### ISSUE TITLE
Custom messages may cause garbled text if echoed too early

### ISSUE THREAD

**Issue by lida2003** [OpenIPC/msposd#22]
If I use command below in rc.local script, then the message seems to be garbled.

- `echo "Monitor... &L04 &F28 &F22 CPU:&C &B temp:&T" >/tmp/MSPOSD.msg`

So I add a cron task evey 1 minute, then it will be ok. I don't know why?

- at the very begining, just after the initial png file display.
![b0d0b68f8a7eafffe68f06092c47326](https://github.com/user-attachments/assets/58024dae-4dae-410f-92d3-df80f6778062)

- after 60seconds, then it's OK
![507b30df2b415b4c7cac0d0fc0fae86](https://github.com/user-attachments/assets/18a091fb-9079-442f-8766-14e8155f0f03)

--- EDIT: modified commands `echo "Monitor... &L04 &F22 CPU:&C &B temp:&T" >/tmp/MSPOSD.msg`, the problem still exist. It's NOT 100% issue, something like 80% error rate.

**Comment by tipoman9** [comment]
I don't get it, where is the garbled text?

**Comment by henkwiedig** [comment]
I'm guessing it's the discrepancy between the green MSPOSD.msg wich looks a lot like the one from the Adaptive Link package and the custom white one at the bottom "Monitor .... "

@lida2003 do you use Adaptive Link ? This package updates the MSPOSG.msg constantly. You will not be able to use a custom one or change out Adaptive Link config to skip that.

**Comment by lida2003** [comment]
@henkwiedig YES, I have just installed adaptive link. Thanks, I see the code updating MSPOSG.msg. That's great!
