### ISSUE TITLE
_DEBUG_x86 MACRO optimization & clarification

### ISSUE THREAD

**Issue by lida2003** [OpenIPC/msposd#33]
I have searched code, and it exists in two places:

May be we can optimze this:

https://github.com/OpenIPC/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/osd/util/Render_x86.c#L1-L2

https://github.com/OpenIPC/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/osd/util/Render_x86.c#L73-L75

**Comment by lida2003** [comment]
I think it can be removed @henkwiedig . what do you think?

As we have this option:

https://github.com/OpenIPC/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/msposd.c#L114

https://github.com/OpenIPC/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/msposd.c#L1350-L1353

https://github.com/OpenIPC/msposd/blob/cabc6b8ade29112f63a5a8a5621e02240d0c3a13/osd/util/Render_x86.c#L71-L72

**Comment by lida2003** [comment]
Please review https://github.com/OpenIPC/msposd/pull/34

**Comment by henkwiedig** [comment]
closed by https://github.com/OpenIPC/msposd/pull/34
