### ISSUE TITLE
UTC time is not available in all regions

### ISSUE THREAD

**Issue by longcat99** [OpenIPC/msposd#36]
https://github.com/OpenIPC/msposd/blob/3dca811285f3784e9c79458ea3a26c1552c5879b/osd.c#L1186

time_t t = time(NULL);
struct tm *tm = localtime(&t);  // 改为 localtime 获取本地时间
strftime(s, 64, timefmt, tm);

**Comment by lida2003** [comment]
@longcat99 Good catch, https://github.com/OpenIPC/msposd/pull/39 , Hope it will be accepted.

**Comment by tipoman9** [comment]
Merged, thanks!

**Comment by lida2003** [comment]
I have found an issue when it comes to IPC.
OpenIPC don't have that much flash rom for zoneinfo, and it was NOT build in firmware.


It's OK for my raspberry Pi, but NOT OK for my OpenIPC camera. @tipoman9 @longcat99 


```bash
$ du -sh /usr/share/zoneinfo
5.8M    /usr/share/zoneinfo
```
