### ISSUE TITLE
Error copyRectI4 from 0:1944  to 1416:864  srcWidth:24, srcHeight:9216, destWidth:1280, destHeight:720

### ISSUE THREAD

**Issue by husanboyqodirov** [OpenIPC/msposd#41]
With Ardupilot, when I execute msposd on OpenIPC, the OSD characters are blinking frequently on the video and I see this message on console:
............
Error copyRectI4 from 0:1944  to 1416:864  srcWidth:24, srcHeight:9216, destWidth:1280, destHeight:720
Error copyRectI4 from 0:6048  to 1440:864  srcWidth:24, srcHeight:9216, destWidth:1280, destHeight:720
Error copyRectI4 from 0:8028  to 1464:864  srcWidth:24, srcHeight:9216, destWidth:1280, destHeight:720
............

I'm using Ardupilot fonts.

Also, all OSD characters are being updated but AHI is not changing.

**Comment by tipoman9** [comment]
https://github.com/OpenIPC/msposd?tab=readme-ov-file#diagnosing

**Comment by husanboyqodirov** [comment]
Solved! Here's the steps:

On OpenIPC terminal type
`top`
and find the PID of mavfwd process.
Close top and
`kill {mavfwd PID}`

and then execute msposd

**Comment by husanboyqodirov** [comment]
Solved! Here's the steps:

On OpenIPC terminal type
top
and find the PID of mavfwd process.
Close top and
kill {mavfwd PID}
e.g.
kill 750

and then execute msposd
